#!/bin/bash
# Script de instalación y compilación de Colabb Terminal C++

echo "=== Instalación de Dependencias ==="
echo "Ejecuta este comando e ingresa tu contraseña cuando se solicite:"
echo ""
echo "sudo apt install -y build-essential cmake pkg-config libgtk-3-dev libvte-2.91-dev libcurl4-openssl-dev libsecret-1-dev"
echo ""
echo "=== Compilación del Proyecto ==="
echo "Una vez instaladas las dependencias, ejecuta:"
echo ""
echo "cd colabb-cpp"
echo "mkdir -p build && cd build"
echo "cmake .."
echo "make -j\$(nproc)"
echo ""
echo "=== Ejecución ==="
echo "Para ejecutar la aplicación:"
echo ""
echo "./colabb"
echo ""
echo "=== Instalación del Sistema (Opcional) ==="
echo "Para instalar en /usr/local/bin:"
echo ""
echo "sudo make install"
echo ""
