#ifndef COLABB_VERSION_HPP
#define COLABB_VERSION_HPP

#define COLABB_VERSION_MAJOR 1
#define COLABB_VERSION_MINOR 0
#define COLABB_VERSION_PATCH 0
#define COLABB_VERSION "1.0.0"

#endif // COLABB_VERSION_HPP
